{{- if .Values.serviceAccounts.data.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    snappyflow/compname: ES
    snappyflow/appname: QA-Admin-stage
    app: {{ template "elasticsearch.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.data.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "elasticsearch.data.fullname" . }}
{{- end }}
